version: "3"

services:
  springboot:
    image: .
    environment:
      TZ: "Asia/Seoul"

  nginx:
    container_name: nginx
    image: nginx:1.14
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/service-url.inc:/etc/nginx/service-url.inc
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/frontend/build:/home/ubuntu/frontend/build